services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    environment:
      - SERVICE_NAME=user-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - NODE_ENV=development
    depends_on:
      - otel-collector
    networks:
      - observability-net

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"
    environment:
      - SERVICE_NAME=order-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - NODE_ENV=development
    depends_on:
      - user-service
      - otel-collector
    networks:
      - observability-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - observability-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - observability-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - observability-net

  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "5775:5775"  # For thrift compact protocol
      - "6831:6831/udp"  # For UDP protocol
      - "6832:6832/udp"  # For UDP protocol
      - "5778:5778"  # For HTTP protocol
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # For gRPC endpoint
      - "14268:14268"  # For HTTP endpoint (deprecated)
      - "14250:14250"  # gRPC





  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.85.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888"
      - "13133:13133"
      - "4317:4317"
      - "4318:4318"
      - "55670:55679"
    depends_on:
      - jaeger
    networks:
      - observability-net



networks:
  observability-net:
